version: "3.3"

services:
        mysql:
                image: mariadb:latest
                restart: always
                ports:
                  - "3306"
                environment:
                  MYSQL_ROOT_PASSWORD: MyDBRoot123
                  MYSQL_DATABASE: php
                  MYSQL_USER: php
                  MYSQL_PASSWORD: php
                networks:
                  - app-network
        myredis:
                image: redis:latest
                restart: always
                ports:
                  - "6379"
                networks:
                  - app-network
        myphp:
                build: ./src/php
                restart: always
                volumes:
                  - $HOME/cca2/src:/var/www/html
                links:
                  - myredis
                  - mysql
                restart: always
                ports:
                  - "9000"
                depends_on:
                  - mysql
                  - myredis
                networks:
                  - app-network
        mynginx:
                image: nginx:latest
                restart: always
                volumes:
                  - $HOME/cca2/src:/var/www/html
                  - $HOME/cca2/src/nginx.ini:/etc/nginx/conf.d/default.conf
                  - $HOME/cca2/src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
                  - $HOME/cca2/src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
                ports:
                  - "8080:80"
                links:
                  - myphp
                networks:
                  - app-network
networks:
        app-network:
           driver: bridge
